### ISSUE TITLE
Null pointer app crash in ViewMapFragment.java

### ISSUE THREAD

**Issue by mkrupczak3** [josh75337/CS-2340-Block-Beach-Boys#26]
Description:
A null pointer call can occur with mLastKnownLocation being null, crashing the app

Steps to Reproduce:
Boot up an android device that has not had a location check performed. Open the app once and give it location permissions. Reset the app, and upon trying to navigate to the sightings list the app will crash

Fix:
Do a null check on mLastKnownLocation before trying to call any of its methods

10-23 22:15:35.121 4649-4649/com.ohrats.bbb.ohrats E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.ohrats.bbb.ohrats, PID: 4649
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                         at com.ohrats.bbb.ohrats.ViewMapFragment$2.onComplete(ViewMapFragment.java:97)
                                                                         at com.google.android.gms.tasks.zzf.run(Unknown Source)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by mchan60** [comment]
we cant actually use that atm cuz of gradle issues...i pushed incomplete stuff so josh could take a look at what im using and try and fix

**Comment by mkrupczak3** [comment]
Unless I'm mistaken, this isn't a gradle issue but rather a null pointer right?

**Comment by mkrupczak3** [comment]
If I open maps and try to acquire my location, then open the app, it runs without a crash

**Comment by mkrupczak3** [comment]
If you try to run the app first thing after launching your device, it crashes

**Comment by mkrupczak3** [comment]
I think this is just a case of performing a simple null check on mLastKnownLocation.
mLastKnownLocation will be null if the device hasn't acquired a location since being turned on

**Comment by mchan60** [comment]
no like we were just trying to fix gradle issues so pushed incomplete code. like actually ignore it rn

**Comment by mchan60** [comment]
if i you want to test the map use the previous push

**Comment by mkrupczak3** [comment]
Ah, ok. What's wrong with gradle?

**Comment by mchan60** [comment]
josh fixed it persay however now the app runs super slow

**Comment by mkrupczak3** [comment]
Think this has been fixed as of 58ea206ce1f188e52387f5e417fc80121fcb3f2b at least
